name: ${project.name}
version: ${project.version}
main: ${rootPackage}.LuckyBlocksPlugin
api-version: 1.16
load: STARTUP
depend: [ ZarazaCommon, CustomStuff ]
authors: [ Dmitrykersh ]
description: ${project.description}
